Deep Learning Task 1

Written By: Karin Fridkin and Rotem ----

Description: building a simple neural network “from scratch”.

In [1]:
import numpy as np
import tensorflow as tf
from dnn_model import l_layer_model, predict

In [ ]:
NUMBER_OF_CLASSES = 10
def load_and_preprocess_mnist():
    # Load
    (x_train_full, y_train_full), (x_test, y_test) = tf.keras.datasets.mnist.load_data(path='mnist.npz')
    
    # Flatten: (60000, 28, 28) -> (784, 60000) and normalize to [0, 1]
    x_train_full = x_train_full.reshape(-1, 784).T / 255.0
    x_test       = x_test.reshape(-1, 784).T       / 255.0
    
    # One-hot encode labels: (60000,) -> (10, 60000)
    y_train_full = np.eye(NUMBER_OF_CLASSES)[y_train_full].T
    y_test       = np.eye(NUMBER_OF_CLASSES)[y_test].T
    
    # Split train -> train (80%) + validation (20%)
    m             = x_train_full.shape[1]
    m_val         = int(m * 0.2)
    
    np.random.seed(42)
    permutation   = np.random.permutation(m)
    train_idx     = permutation[m_val:]
    val_idx       = permutation[:m_val]
    
    x_train, y_train = x_train_full[:, train_idx], y_train_full[:, train_idx]
    x_val,   y_val   = x_train_full[:, val_idx],   y_train_full[:, val_idx]
    
    # Summary
    print(f"Train: {x_train.shape} | Val: {x_val.shape} | Test: {x_test.shape}")
    
    return x_train, y_train, x_val, y_val, x_test, y_test

Train: (784, 48000) | Val: (784, 12000) | Test: (784, 10000)


(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], shape=(784, 48000)),
 array([[0., 1., 0., ..., 1., 1., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], shape=(10, 48000)),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], shape=(784, 12000)),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.],
        ...,
        [1., 0., 0., ..., 0., 1., 0.],
        [0., 0., 1., ...,